#!/bin/bash
source .venv/bin/activate
export MODEL_VALUE_ENABLED=true
export ENABLE_MODEL_VALUE_TRADING=true
export MODEL_VALUE_EDGE_MODE=residual
export MODEL_VALUE_MIN_EDGE=0.01
export MODEL_VALUE_CONFIRM_MIN_EDGE=0.01
export MODEL_VALUE_CONFIRM_MAX_AGE_SEC=90
export MODEL_VALUE_CONFIRM_MAX_ASK_WORSEN=0.02
export MODEL_VALUE_MIN_GAME_TIME_SEC=420
export MODEL_VALUE_MAX_GAME_TIME_SEC=2400
export MODEL_VALUE_MAX_SPREAD=0.05
export MODEL_VALUE_MAX_BOOK_AGE_MS=5000
export MODEL_VALUE_TRADE_USD=5
export MODEL_VALUE_MAX_OPEN_POSITIONS=1
export MAX_BOOK_AGE_MS=5000
export MAX_SPREAD=0.05
export VALUE_ENGINE_ENABLED=false
export EVENT_TRIGGERED_VALUE_ENABLED=false
export DSWING_ENABLED=false
export LIVE_TRADING=false
export ENABLE_REAL_LIVE_TRADING=false
export PAPER_MODE=live_parity

python3 supervisor.py
